### ISSUE TITLE
Unable to build and download image

### ISSUE THREAD

**Issue by ssaikiran123** [johnlonganecker/libpostal-rest-docker#11]
Hello @johnlonganecker 

I am unable to build image from docker file please help me

root@saiki-virtual-machine:~/libpostal-rest-docker-master# docker run -d -p 8080:8080 libpostal-rest
Unable to find image 'libpostal-rest:latest' locally
docker: Error response from daemon: pull access denied for libpostal-rest, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by johnlonganecker** [comment]
you will need to clone this repo, built it then use your command above:

```
git clone https://github.com/johnlonganecker/libpostal-rest-docker.git
cd libpostal-rest-docker
docker build -t libpostal-rest .
docker run -d -p 8080:8080 libpostal-rest
```
