### ISSUE TITLE
How to configure the other ports? 

### ISSUE THREAD

**Issue by selva221724** [johnlonganecker/libpostal-rest-docker#12]
Hi there,

my question will be silly, I want to change the port 8080 to 8083. i followed these steps,

1 . in docker file ==> EXPOSE 8083
2. in docker run==> 8083:8083

is that right? 

Please let me now if i mislead the way to do it.

**Comment by johnlonganecker** [comment]
The easiest way in my opinion is just specify when you run the container. For example

`docker run -p 8083:8080 ...`

8083 -> the port you want to talk to
8080 -> the internal app listens on this port

**Comment by selva221724** [comment]
That's great. Thanks a lot @johnlonganecker appreciate that!!!
