### ISSUE TITLE
Push image to Docker hub?

### ISSUE THREAD

**Issue by jackturnbull** [johnlonganecker/libpostal-rest-docker#3]
Hi, thanks for the work!

Do you plan on pushing the pre-built image to Docker hub? It'd make using docker-compose a little more intuitive as well as reducing the initial build time quite significantly, where the latter is only an issue really for our uncached CI pipeline (thank you CircleCI).

If not, do you know any valid reasons to not push this up? You might know of some dragon that I don't type thing!

Cheers!

**Comment by omab** [comment]
@jackturnbull, like this one https://hub.docker.com/r/fuxingloh/libpostal-rest-docker/ ?

**Comment by jackturnbull** [comment]
Good catch, cheers!

**Comment by johnlonganecker** [comment]
thanks @omab!

**Comment by omab** [comment]
@johnlonganecker, thank you, this project saved me some time by doing exactly what I was needing.

**Comment by johnlonganecker** [comment]
👍  my pleasure
