### ISSUE TITLE
Expose to local network

### ISSUE THREAD

**Issue by pds-amd** [johnlonganecker/libpostal-rest-docker#4]
Good day

I am new to the world of docker. I have successfully gotten your container working, but now I would like to expose the rest endpoint to my local network. Is it as simple as using a different set of flags when running the container?

Thanks for your help!

**Comment by pds-amd** [comment]
If I try a different container I have success and can access it on other machines on the network:

```
root@ubuntu:/home/pdossantos# docker run -d -p 80:80 nginx
738ee593d46a1f0b401b25707a1d136daecb22bc8ef0c34cd6258450c21a1641
root@ubuntu:/home/pdossantos# curl localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
However, trying the same with libpostal-rest fails:

```
root@ubuntu:/home/pdossantos# docker run -d -p 80:80 libpostal-rest
02b6ccb2243f0c1797e3cccbd351150aefc0cc172153a668284debeab85cce2a
root@ubuntu:/home/pdossantos# curl -X POST -d '{"query": "100 main st buffalo ny"}' localhost/parser
curl: (56) Recv failure: Connection reset by peer
```

**Comment by pds-amd** [comment]
Final message... 

Please consider this an oversight on my part... I am very new to web development and didn't realise a POST is constructed differently than a GET.

By running:

` docker run -d -p 80:8080 libpostal-rest`
 
And then using the following in Python I am able to work with the response across the local network on a machine other than the localhost:

```
>>> import requests
>>> url = "http://172.16.22.49:80/parser"
>>> json = {"query": "100 main st buffalo ny"}
>>> requests.post(url, json=json, headers={}, cookies={}).json()
[{u'label': u'house_number', u'value': u'100'},
 {u'label': u'road', u'value': u'main st'},
 {u'label': u'city', u'value': u'buffalo'},
 {u'label': u'state', u'value': u'ny'}]
>>> 
```

**Comment by johnlonganecker** [comment]
Thanks a lot for your question! no worries all these things are complicated. I appreciate you following up with an answer to your own question and then closing the issue!

Best of luck.
