### ISSUE TITLE
Dockerfile Issue

### ISSUE THREAD

**Issue by mishra123** [johnlonganecker/libpostal-rest-docker#6]
In the Dockerfile, the following step has an issue that "Remote branch $COMMIT not found in upstream origin. 
RUN git clone https://github.com/openvenues/libpostal -b $COMMIT

To resolve this, I removed the "-b $COMMIT" which cloned the repo but then on the next command "COPY ./*.sh /libpostal/" failed as well with the error message "COPY failed: no source files were specified". Can you help me fix this issue or update the dockerfile if it needs to.

All the *.sh files are in https://github.com/johnlonganecker/libpostal-rest-docker whereas we are  not cloning this repo anywhere. That might be the reason that it doesn't find any .sh files in there. I might be doing something wrong. 
Thanks

**Comment by johnlonganecker** [comment]
Hey @mishra123 thanks for letting me know. I will take a look at it later this evening.

**Comment by mishra123** [comment]
Thanks @johnlonganecker

**Comment by johnlonganecker** [comment]
So this project assumes you are in the root of the projects directory. For example:

```
git clone git@github.com:johnlonganecker/libpostal-rest-docker.git 
cd libpostal-rest-docker
docker build -t libpostal-rest .
docker run -d -p 8080:8080 libpostal-rest
```

Are you only copying the Dockerfile out of the project and trying to run the build off of that?

**Comment by mishra123** [comment]
Yes, it's resolved. Thank you very much!

**Comment by johnlonganecker** [comment]
Great! thanks for submitting the issue and closing it.
