### ISSUE TITLE
Error from image build

### ISSUE THREAD

**Issue by ujja** [johnlonganecker/libpostal-rest-docker#8]
Hello,

Image build (docker build -t libpostal-rest .) is not working to me:

Cloning into 'libpostal'...
Removing intermediate container e26bc317e4aa
 ---> 25a37ca6b01e
Step 7/12 : COPY ./*.sh /libpostal/
 ---> 0a63eb04d20b
Step 8/12 : WORKDIR /libpostal
 ---> Running in d1399ee7838d
Removing intermediate container d1399ee7838d
 ---> 7c955f9bee03
Step 9/12 : RUN ./build_libpostal.sh
 ---> Running in f8f76c8fc21a
/usr/bin/env: 'bash\r': No such file or directory
The command '/bin/sh -c ./build_libpostal.sh' returned a non-zero code: 127

**Comment by johnlonganecker** [comment]
Hey Ujja, sorry for the delayed response. Are you still experiencing this problem? When you use:

```
docker build -t libpostal-rest .
```

It is using the latest code from libpostal, which may or may not be stable. You could also add this flag to the command to pick a previous stable commit.

```
--build-arg COMMIT=<sha1 hash from libpostal repo>
```

An example:
```
docker build -t libpostal-rest --build-arg COMMIT=e816b4f77e8c6a7f35207ca77282ffab3712c5b6 .
```

**Comment by johnlonganecker** [comment]
If you are still experiencing this issue let me know I can take a look at it.
