### ISSUE TITLE
Error builiding the image

### ISSUE THREAD

**Issue by giampaolotrapasso** [johnlonganecker/libpostal-rest-docker#9]
Hi and thanks for this interesting work.

This is what I get checkout this project on master and try to run
`docker build -t libpostal-rest .`

```
Step 10/12 : RUN ./build_libpostal_rest.sh
 ---> Running in a3c3398da856
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 87.0M  100 87.0M    0     0  81868      0  0:18:34  0:18:34 --:--:-- 22915
go1.8.1.linux-amd64.tar.gz: OK
# pkg-config --cflags libpostal
Package libpostal was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpostal.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpostal' found
pkg-config: exit status 1
# pkg-config --cflags libpostal
Package libpostal was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpostal.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpostal' found
pkg-config: exit status 1
```

Any idea on this? Can you reproduce it?

**Comment by johnlonganecker** [comment]
I just ran it and I was able to build it:

Step 10/12 : RUN ./build_libpostal_rest.sh
 ---> Running in 4d71e38a29a5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 87.0M  100 87.0M    0     0  27.8M      0  0:00:03  0:00:03 --:--:-- 27.8M
go1.8.1.linux-amd64.tar.gz: OK
Removing intermediate container 4d71e38a29a5
 ---> 1d6b1151f465

Did a previous step have an issue? Perhaps step 9.

**Comment by giampaolotrapasso** [comment]
You were right. I launched it again and before step 10 I got

```
Makefile:4125: recipe for target 'all-local' failed
make[1]: Leaving directory '/libpostal/src'
make[1]: *** [all-local] Error 123
Makefile:458: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
Removing intermediate container cd41146db807
 ---> 69379259464e
```

The full log is [here](https://gist.github.com/giampaolotrapasso/95d15602b727141bd50bae6ba0053638)

Do I need to use a different libpostal commit to be successful?

**Comment by johnlonganecker** [comment]
I ran it with the latest libpostal commit. Off the top of my head I am not sure what would be causing this issue. what commit are you using of this repo?

What version of docker are you running?

Would it be possible for you to remove all images and then re-run the build?

**This will delete all images off of your machine**
```
docker images -aq | xargs docker rmi -f
docker pull index.docker.io/ubuntu:16.04
```

My dockerfile is based off of  `ubuntu:16.04` https://github.com/johnlonganecker/libpostal-rest-docker/blob/master/Dockerfile#L1 which comes from hub.docker.com I am wondering if your `ubuntu:16.04` is not coming from there and getting a slightly different docker image which causes the compiling of libpostal to fail.

**Comment by giampaolotrapasso** [comment]
I've tried as you suggested, cloning your project again and using latest commit. The result unfortunately is the same, you can see it [here](https://gist.github.com/giampaolotrapasso/9a72b56ba6616f0d8e2c6d9c4260c070).

I'm running Docker on OsX, my version is (31259). Tomorrow I'l try to run in on Docker on a Linux machine and see if there are some differences. By the way, I think I'm pulling from the docker hub as you. What is your configuration?

**Comment by johnlonganecker** [comment]
what do you get when you run `docker pull index.docker.io/ubuntu:16.04`?

**Comment by giampaolotrapasso** [comment]
I get this
`✘-127 ~/dev/sandbox/libpostal-rest-docker [master|✔]
11:05 $ docker pull index.docker.io/ubuntu:16.04
16.04: Pulling from library/ubuntu
Digest: sha256:599b12ff9760b68095db78eaf1260e53c8839ca5ff590fb4a3d2f79c8d459b2b
Status: Image is up to date for ubuntu:16.04`

**Comment by giampaolotrapasso** [comment]
I've tried to build the image on a Ubuntu box and everything was ok.

**Comment by johnlonganecker** [comment]
I run everything on my MacBook using docker desktop. I am sorry I don't know what the issues is on your machine. Are you using docker desktop?

**Comment by giampaolotrapasso** [comment]
These are my settings. 

<img width="581" alt="Schermata 2019-05-18 alle 21 13 33" src="https://user-images.githubusercontent.com/7675964/57974015-eb939200-79b1-11e9-8cf3-4e0f7b8ceed1.png">

**Comment by juancarlosbaezpozos** [comment]
I had the same error but was fixed adding the last line. this is my sh content

#!/usr/bin/env bash
./bootstrap.sh
mkdir -p /opt/libpostal_data
./configure --datadir=/opt/libpostal_data
make -j4
make install
ldconfig
pkg-config --cflags libpostal

**Comment by johnlonganecker** [comment]
👍 thanks for sharing I will check it out. I wasn't able to re-produce the error but if this doesn't break anything I will just include it.

**Comment by stexyz** [comment]
Was able to build updating the Dockerfile to newer Ubuntu (18.04) and replacing the (super)old Go runtime from `go1.8.1.linux-amd64.tar.gz` to `go1.15.11.linux-amd64.tar.gz` in `build_libpostal_rest.sh`.

**Comment by johnlonganecker** [comment]
@stexyz do you mind submitting a PR?
